import readline from 'readline';
import { program, Command } from 'commander';
import { readFile, writeFile, mkdir } from 'fs/promises';
import { existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { homedir } from 'os';
import { spawn } from 'child_process';
import http from 'http';
import https from 'https';
import { fileURLToPath } from 'url';
import WebSocket from 'ws';
import crypto from 'crypto';

// Get version from package.json
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageJsonPath = join(__dirname, 'package.json');
let cliVersion = '0.0.0';
try {
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
  cliVersion = packageJson.version || '0.0.0';
} catch (error) {
  // Fallback if package.json can't be read - try to read from parent directory
  try {
    const parentPackageJsonPath = join(__dirname, '..', 'package.json');
    const packageJson = JSON.parse(readFileSync(parentPackageJsonPath, 'utf8'));
    cliVersion = packageJson.version || '0.0.0';
  } catch (e) {
    // If both fail, use default
  }
}

// Session ID generation is now handled by the server
// This function is kept for backward compatibility but should not be used for new sessions
function generateSessionId() {
  // DEPRECATED: Session IDs should be generated by the server
  // This is only used as a fallback if server creation fails
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  let result = 'vibex-';
  
  // Use crypto.randomBytes for cryptographically secure random generation
  const randomBytes = crypto.randomBytes(12);
  for (let i = 0; i < 12; i++) {
    result += chars[randomBytes[i] % chars.length];
  }
  
  return result;
}

function normalizeSessionId(sessionId) {
  if (!sessionId) return null;
  // If it doesn't start with 'vibex-', add it
  if (!sessionId.startsWith('vibex-')) {
    return `vibex-${sessionId}`;
  }
  return sessionId;
}

function deriveSocketUrl(webUrl) {
  const url = new URL(webUrl);
  
  // For localhost, use Workers dev server
  if (url.hostname === 'localhost' || url.hostname === '127.0.0.1') {
    return 'ws://localhost:8787';
  } 
  // For vibex.sh domains, use Workers WebSocket endpoint
  else if (url.hostname.includes('vibex.sh')) {
    // Use Cloudflare Workers WebSocket endpoint
    const workerUrl = process.env.VIBEX_WORKER_URL || 'https://ingest.vibex.sh';
    return workerUrl.replace('https://', 'wss://').replace('http://', 'ws://');
  } 
  // For other domains, derive from web URL
  else {
    const workerUrl = process.env.VIBEX_WORKER_URL || webUrl.replace(url.hostname, `ingest.${url.hostname}`);
    return workerUrl.replace('https://', 'wss://').replace('http://', 'ws://');
  }
}

function getUrls(options) {
  const { local, web, socket, server } = options;
  
  // Priority 1: Explicit --web and --socket flags (highest priority)
  if (web) {
    return {
      webUrl: web,
      socketUrl: socket || deriveSocketUrl(web),
    };
  }
  
  // Priority 2: --server flag (shorthand for --web)
  if (server) {
    return {
      webUrl: server,
      socketUrl: socket || deriveSocketUrl(server),
    };
  }
  
  // Priority 3: --local flag
  if (local) {
    return {
      webUrl: process.env.VIBEX_WEB_URL || 'http://localhost:3000',
      socketUrl: process.env.VIBEX_SOCKET_URL || socket || 'ws://localhost:8787',
    };
  }
  
  // Priority 4: Environment variables
  if (process.env.VIBEX_WEB_URL) {
    return {
      webUrl: process.env.VIBEX_WEB_URL,
      socketUrl: process.env.VIBEX_SOCKET_URL || socket || deriveSocketUrl(process.env.VIBEX_WEB_URL),
    };
  }
  
  // Priority 5: Production defaults
  // Use Worker WebSocket endpoint instead of old Socket.io server
  const defaultWorkerUrl = process.env.VIBEX_WORKER_URL || 'https://ingest.vibex.sh';
  return {
    webUrl: 'https://vibex.sh',
    socketUrl: socket || defaultWorkerUrl.replace('https://', 'wss://').replace('http://', 'ws://'),
  };
}

function getConfigPath() {
  // Check for custom config path from environment variable
  if (process.env.VIBEX_CONFIG_PATH) {
    return process.env.VIBEX_CONFIG_PATH;
  }
  // Default: ~/.vibex/config.json
  const configDir = join(homedir(), '.vibex');
  return join(configDir, 'config.json');
}

async function getStoredToken() {
  try {
    const configPath = getConfigPath();
    if (existsSync(configPath)) {
      const config = JSON.parse(await readFile(configPath, 'utf-8'));
      return config.token || null;
    }
  } catch (error) {
    // Ignore errors (file doesn't exist or invalid JSON)
  }
  return null;
}

function getStoredConfig() {
  try {
    const configPath = getConfigPath();
    if (existsSync(configPath)) {
      return JSON.parse(readFileSync(configPath, 'utf-8'));
    }
  } catch (error) {
    // Ignore errors
  }
  return null;
}

async function storeToken(token, webUrl = null) {
  try {
    const configPath = getConfigPath();
    const configDir = join(homedir(), '.vibex');
    if (!existsSync(configDir)) {
      await mkdir(configDir, { recursive: true });
    }
    
    const config = {
      token,
      ...(webUrl && { webUrl }), // Store webUrl if provided
      updatedAt: new Date().toISOString(),
    };
    
    await writeFile(configPath, JSON.stringify(config, null, 2), 'utf-8');
    return true;
  } catch (error) {
    console.error('Failed to store token:', error.message);
    return false;
  }
}

async function handleLogin(webUrl) {
  const configPath = getConfigPath();
  const existingConfig = getStoredConfig();
  
  console.log('\n  🔐 vibex.sh CLI Authentication\n');
  console.log(`  📁 Config location: ${configPath}`);
  
  if (existingConfig?.token) {
    console.log(`  ⚠️  You already have a token stored. This will replace it.\n`);
  }
  
  const tempToken = `temp_${Date.now()}_${Math.random().toString(36).substring(7)}`;
  const authUrl = `${webUrl}/api/cli-auth?token=${tempToken}`;
  
  console.log('  Opening browser for authentication...\n');
  console.log(`  If browser doesn't open, visit: ${authUrl}\n`);
  
  // Open browser
  const platform = process.platform;
  let command;
  if (platform === 'darwin') {
    command = 'open';
  } else if (platform === 'win32') {
    command = 'start';
  } else {
    command = 'xdg-open';
  }
  
  spawn(command, [authUrl], { detached: true, stdio: 'ignore' });
  
  // Poll for token
  console.log('  Waiting for authentication...');
  const maxAttempts = 60; // 60 seconds
  let attempts = 0;
  
  while (attempts < maxAttempts) {
    await new Promise(resolve => setTimeout(resolve, 1000));
    attempts++;
    
    try {
      const response = await httpRequest(`${webUrl}/api/cli-auth?token=${tempToken}`, {
        method: 'GET',
      });
      if (response.ok) {
        const data = await response.json();
        if (data.success && data.token) {
          await storeToken(data.token, webUrl);
          const configPath = getConfigPath();
          console.log('\n  ✅ Authentication successful!');
          console.log(`  📁 Token saved to: ${configPath}`);
          console.log(`  💡 This token will be used automatically for future commands.\n`);
          return data.token;
        }
      }
    } catch (error) {
      // Continue polling
    }
  }
  
  console.log('\n  ⏱️  Authentication timeout. Please try again.\n');
  process.exit(1);
}

function httpRequest(url, options) {
  return new Promise((resolve, reject) => {
    const urlObj = new URL(url);
    const isHttps = urlObj.protocol === 'https:';
    const httpModule = isHttps ? https : http;
    
    const req = httpModule.request(url, options, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          resolve({ ok: res.statusCode >= 200 && res.statusCode < 300, status: res.statusCode, json: () => Promise.resolve(parsed) });
        } catch (e) {
          resolve({ ok: res.statusCode >= 200 && res.statusCode < 300, status: res.statusCode, json: () => Promise.resolve({}) });
        }
      });
    });
    
    req.on('error', reject);
    if (options.body) {
      req.write(options.body);
    }
    req.end();
  });
}

async function claimSession(sessionId, token, webUrl) {
  if (!token) return null; // Return null instead of false to indicate no claim attempted
  
  try {
    // Normalize session ID before claiming
    const normalizedSessionId = normalizeSessionId(sessionId);
    const response = await httpRequest(`${webUrl}/api/auth/claim-session-with-token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        sessionId: normalizedSessionId,
        token,
      }),
    });
    
    if (response.ok) {
      // Parse response to get auth code
      const responseData = await response.json();
      return responseData.authCode || null;
    }
    
    return null;
  } catch (error) {
    return null;
  }
}

// Removed getSessionAuthCode - auth codes should only come from:
// 1. claim-session-with-token response (for claimed sessions)
// 2. socket.io session-auth-code event (for unclaimed sessions)
// Never fetch auth codes via public API endpoint - security vulnerability 

function printBanner(sessionId, webUrl, authCode = null) {
  const dashboardUrl = authCode 
    ? `${webUrl}/${sessionId}?auth=${authCode}`
    : `${webUrl}/${sessionId}`;
  
  console.log('\n');
  console.log('  ╔═══════════════════════════════════════╗');
  console.log('  ║         🔍 vibex.sh is watching...    ║');
  console.log('  ╚═══════════════════════════════════════╝');
  console.log('\n');
  console.log(`  Session ID: ${sessionId}`);
  if (authCode) {
    console.log(`  Auth Code:  ${authCode}`);
  }
  console.log(`  Dashboard:  ${dashboardUrl}`);
  console.log('\n');
}

async function main() {
  // Handle --version flag early (before commander parses)
  const allArgs = process.argv;
  const args = process.argv.slice(2);
  
  // Check for --version or -V flag
  if (allArgs.includes('--version') || allArgs.includes('-V') || args.includes('--version') || args.includes('-V')) {
    console.log(cliVersion);
    process.exit(0);
  }
  
  // Handle login command separately - check BEFORE commander parses
  // Check process.argv directly - look for 'login' as a standalone argument
  // This must happen FIRST, before any commander parsing
  // Check if 'login' appears anywhere in process.argv (works with npx too)
  const hasLogin = allArgs.includes('login') || args.includes('login');
  
  if (hasLogin) {
    // Find login position to get args after it
    const loginIndex = args.indexOf('login');
    const loginArgs = loginIndex !== -1 ? args.slice(loginIndex + 1) : [];
    
    // Create a separate command instance for login
    const loginCmd = new Command();
    loginCmd
      .option('-l, --local', 'Use localhost')
      .option('--web <url>', 'Web server URL')
      .option('--server <url>', 'Shorthand for --web');
    
    // Parse only the options (args after 'login')
    if (loginArgs.length > 0) {
      loginCmd.parse(['node', 'vibex', ...loginArgs], { from: 'user' });
    } else {
      loginCmd.parse(['node', 'vibex'], { from: 'user' });
    }
    
    const options = loginCmd.opts();
    const { webUrl } = getUrls(options);
    await handleLogin(webUrl);
    process.exit(0);
  }

  program
    .version(cliVersion, '-v, --version', 'Display version number')
    .option('-s, --session-id <id>', 'Reuse existing session ID')
    .option('-l, --local', 'Use localhost (web: 3000, socket: 3001)')
    .option('--web <url>', 'Web server URL (e.g., http://localhost:3000)')
    .option('--socket <url>', 'Socket server URL (e.g., http://localhost:3001)')
    .option('--server <url>', 'Shorthand for --web (auto-derives socket URL)')
    .option('--token <token>', 'Authentication token (or use VIBEX_TOKEN env var)')
    .parse();

  const options = program.opts();
  const { webUrl, socketUrl } = getUrls(options);
  
  // Get token from flag, env var, or stored config
  let token = options.token || process.env.VIBEX_TOKEN || await getStoredToken();
  
  let sessionId;
  let authCode = null;
  
  // If session ID is provided, use it (existing session)
  if (options.sessionId) {
    sessionId = normalizeSessionId(options.sessionId);
    
    // If token is available, try to claim the session
    if (token) {
      authCode = await claimSession(sessionId, token, webUrl);
    }
    
    // When reusing a session, show minimal info
    console.log(`  🔍 Sending logs to session: ${sessionId}\n`);
  } else {
    // No session ID provided - create a new anonymous session
    try {
      const createUrl = `${webUrl}/api/sessions/create-anonymous`;
      const response = await httpRequest(createUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });
      
      if (!response.ok) {
        const errorData = await response.json();
        console.error(`  ✗ Failed to create session: ${errorData.message || 'Unknown error'}`);
        process.exit(1);
      }
      
      const data = await response.json();
      sessionId = data.sessionId; // Server-generated unique session ID
      authCode = data.authCode; // Server-generated auth code
      
      // If token is available, claim the session
      if (token) {
        const claimAuthCode = await claimSession(sessionId, token, webUrl);
        if (claimAuthCode) {
          authCode = claimAuthCode;
          console.log('  ✓ Session automatically claimed to your account\n');
        }
      }
      
      // Print banner for new session
      printBanner(sessionId, webUrl, authCode);
      const localFlag = webUrl.includes('localhost') ? ' --local' : '';
      const sessionSlug = sessionId.replace(/^vibex-/, ''); // Remove prefix for example
      console.log('  💡 Tip: Use -s to send more logs to this session');
      console.log(`  Example: echo '{"cpu": 45, "memory": 78}' | npx vibex-sh -s ${sessionSlug}${localFlag}\n`);
    } catch (error) {
      console.error(`  ✗ Error creating session: ${error.message}`);
      process.exit(1);
    }
  }

  let socket = null;
  let isConnected = false;
  let hasJoinedSession = false;
  const logQueue = [];
  let reconnectTimeout = null;
  let reconnectAttempts = 0;
  const maxReconnectDelay = 5000;

  // Connection state management
  let connectionState = 'disconnected'; // disconnected, connecting, connected, closing, closed
  let connectionEstablished = false;
  let connectionLock = false;
  let connectionStartTime = null;

  // Store auth code received from socket
  let receivedAuthCode = authCode;
  
  // Track if this is a new session (not reusing an existing one)
  const isNewSession = !options.sessionId;

  // Graceful shutdown function
  const closeWebSocket = () => {
    return new Promise((resolve) => {
      if (!socket || socket.readyState !== WebSocket.OPEN) {
        if (connectionState === 'connected' || connectionState === 'closing') {
          connectionState = 'closed';
        }
        resolve();
        return;
      }
      
      connectionState = 'closing';
      const closeStartTime = Date.now();
      console.log('  🔄 Initiating graceful WebSocket close...');
      
      const closeTimeout = setTimeout(() => {
        const elapsed = Date.now() - closeStartTime;
        console.log(`  ⚠️  Close handshake timeout after ${elapsed}ms, forcing exit`);
        connectionState = 'closed';
        resolve();
      }, 2000);
      
      // Store original onclose handler
      const originalOnClose = socket.onclose;
      
      socket.onclose = (event) => {
        clearTimeout(closeTimeout);
        const elapsed = Date.now() - closeStartTime;
        connectionState = 'closed';
        connectionEstablished = false;
        console.log(`  ✓ WebSocket closed gracefully (code: ${event.code}, reason: ${event.reason || 'none'}, time: ${elapsed}ms)`);
        
        // Call original handler if it exists
        if (originalOnClose) {
          originalOnClose(event);
        }
        
        resolve();
      };
      
      socket.close(1000, 'Stream ended');
    });
  };

  const connectWebSocket = () => {
    // Prevent multiple simultaneous connections
    if (connectionLock) {
      console.log('  ⚠️  Connection already in progress, skipping...');
      return;
    }
    
    if (connectionState === 'connected' || connectionState === 'connecting') {
      console.log(`  ⚠️  Already ${connectionState}, skipping new connection...`);
      return;
    }
    
    // Clear any existing reconnect timeout to prevent duplicate connections
    if (reconnectTimeout) {
      clearTimeout(reconnectTimeout);
      reconnectTimeout = null;
    }
    
    connectionLock = true;
    connectionState = 'connecting';
    connectionStartTime = Date.now();
    console.log('  🔄 Connecting to WebSocket...');
    
    try {
      // Close existing socket if any (cleanup)
      if (socket && socket.readyState !== WebSocket.CLOSED) {
        try {
          socket.close();
        } catch (e) {
          // Ignore errors when closing
        }
      }
      
      socket = new WebSocket(`${socketUrl}?sessionId=${sessionId}`);

      socket.onopen = () => {
        const connectTime = Date.now() - connectionStartTime;
        connectionLock = false;
        connectionState = 'connected';
        isConnected = true;
        connectionEstablished = true;
        console.log(`  ✓ Connected to server (${connectTime}ms)\n`);
        reconnectAttempts = 0;

        // Join session
        socket.send(JSON.stringify({
          type: 'join-session',
          sessionId,
        }));

        // Set hasJoinedSession immediately - HTTP POST doesn't need WebSocket
        hasJoinedSession = true;
        // Process any queued logs immediately
        while (logQueue.length > 0) {
          const logData = logQueue.shift();
          // Send logs via HTTP POST (non-blocking) instead of WebSocket
          // WebSocket is only for receiving logs
          sendLogViaHTTP(logData);
        }
      };

      socket.onmessage = (event) => {
        try {
          const message = JSON.parse(event.data);

          switch (message.type) {
            case 'join-session-ack':
              console.log('  ✓ Joined session\n');
              break;

            case 'session-auth-code':
              if (message.data && message.data.sessionId === sessionId && message.data.authCode) {
                if (!receivedAuthCode || receivedAuthCode !== message.data.authCode) {
                  receivedAuthCode = message.data.authCode;
                  if (isNewSession) {
                    console.log(`  🔑 Auth Code: ${receivedAuthCode}`);
                    console.log(`  📋 Dashboard: ${webUrl}/${sessionId}?auth=${receivedAuthCode}\n`);
                  }
                }
              }
              break;

            case 'log':
              // Logs are received via WebSocket but sent via HTTP
              break;

            case 'error':
              const errorType = message.error || 'Error';
              const errorMsg = message.message || 'An unexpected error occurred';
              const statusCode = message.statusCode || 0;
              
              // Handle specific error types
              if (errorType === 'Rate Limit Exceeded' || statusCode === 429) {
                console.error('\n  ⚠️  Rate Limit Exceeded');
                console.error(`  ${errorMsg}`);
                if (message.retryAfter) {
                  console.error(`  ⏱️  Retry after: ${message.retryAfter} seconds`);
                }
                console.error('');
                logQueue.length = 0;
              } else if (errorType === 'History Limit Reached' || (statusCode === 403 && errorMsg.includes('History Limit'))) {
                console.error('\n  🚫 History Limit Reached');
                console.error(`  ${errorMsg}`);
                if (message.limit !== undefined && message.current !== undefined) {
                  console.error(`  Current: ${message.current} / ${message.limit} logs`);
                }
                if (message.upgradeRequired) {
                  console.error('  💡 Upgrade to Pro to unlock 30 days retention');
                  console.error('  🌐 Visit: https://vibex.sh/pricing');
                }
                console.error('');
                logQueue.length = 0;
                hasJoinedSession = false;
              } else if (statusCode === 401 || errorType === 'Unauthorized') {
                if (errorMsg.includes('expired')) {
                  console.error('\n  🔑 Token Expired');
                  console.error('  Your authentication token has expired.');
                  console.error('  💡 Run: npx vibex-sh login');
                } else {
                  console.error('\n  🔑 Unauthorized');
                  console.error(`  ${errorMsg}`);
                  console.error('  💡 Run: npx vibex-sh login');
                }
                console.error('');
                logQueue.length = 0;
                hasJoinedSession = false;
              } else if (statusCode === 403 || errorType === 'Forbidden') {
                if (errorMsg.includes('access') || errorMsg.includes('belongs')) {
                  console.error('\n  🚫 Access Denied');
                  console.error(`  ${errorMsg}`);
                  console.error('  💡 This session belongs to another user or is not accessible');
                  console.error('  💡 Make sure you are using the correct token and session ID');
                } else if (errorMsg.includes('archived')) {
                  console.error('\n  🚫 Session Archived');
                  console.error(`  ${errorMsg}`);
                  console.error('  💡 This session is archived and cannot accept new logs');
                } else {
                  console.error('\n  🚫 Forbidden');
                  console.error(`  ${errorMsg}`);
                }
                console.error('');
                logQueue.length = 0;
                hasJoinedSession = false;
              } else if (statusCode === 404 || errorType === 'Not Found') {
                console.error('\n  🔍 Session Not Found');
                console.error(`  ${errorMsg}`);
                console.error('  💡 Make sure the session ID is correct');
                console.error('  💡 Check if the session exists in your dashboard');
                console.error('');
                logQueue.length = 0;
                hasJoinedSession = false;
              } else if (statusCode === 400 || errorType === 'Bad Request') {
                console.error('\n  📝 Bad Request');
                console.error(`  ${errorMsg}`);
                if (errorMsg.includes('sessionId')) {
                  console.error('  💡 Make sure you provided a valid session ID with -s or --session');
                } else if (errorMsg.includes('logs')) {
                  console.error('  💡 Make sure you are sending valid log data');
                }
                console.error('');
                logQueue.length = 0;
              } else if (statusCode >= 500 || errorType === 'Internal Server Error') {
                console.error('\n  🔴 Server Error');
                console.error(`  ${errorMsg}`);
                console.error('  💡 This is a server-side issue. Please try again later.');
                console.error('  💡 If the problem persists, contact support');
                console.error('');
                logQueue.length = 0;
              } else {
                console.error('\n  ✗ Error');
                console.error(`  ${errorType}: ${errorMsg}`);
                if (statusCode) {
                  console.error(`  Status Code: ${statusCode}`);
                }
                console.error('');
                logQueue.length = 0;
              }
              break;

            default:
              // Ignore unknown message types
              break;
          }
        } catch (error) {
          console.error('  ✗ Error parsing message:', error.message);
        }
      };

      socket.onerror = (error) => {
        if (!isConnected) {
          console.error(`  ✗ Connection error: ${error.message || 'websocket error'}`);
          console.error(`  ↻ Trying to connect to: ${socketUrl}`);
          console.error('  ↻ Retrying connection...\n');
        }
      };

      socket.onclose = (event) => {
        connectionLock = false;
        connectionState = 'closed';
        connectionEstablished = false;
        isConnected = false;
        hasJoinedSession = false;
        
        const connectionDuration = connectionStartTime ? Date.now() - connectionStartTime : 0;
        console.log(`  📊 Connection closed (code: ${event.code}, reason: ${event.reason || 'none'}, duration: ${connectionDuration}ms)`);

        // Reconnect logic - only if not a normal closure and not already closing
        if (event.code !== 1000 && connectionState !== 'closing') {
          const delay = Math.min(1000 * Math.pow(2, reconnectAttempts), maxReconnectDelay);
          reconnectAttempts++;
          console.log(`  ↻ Reconnecting in ${delay}ms (attempt ${reconnectAttempts})...\n`);
          
          reconnectTimeout = setTimeout(() => {
            connectWebSocket();
          }, delay);
        } else if (event.code === 1000) {
          console.log('  ✓ Normal closure, no reconnect needed\n');
        }
      };
    } catch (error) {
      connectionLock = false;
      connectionState = 'disconnected';
      connectionEstablished = false;
      console.error(`  ✗ Error creating WebSocket: ${error.message}`);
      console.error(`  ↻ URL: ${socketUrl}`);
      // Retry connection
      reconnectTimeout = setTimeout(() => {
        connectWebSocket();
      }, 1000);
    }
  };

  // Send logs via HTTP POST (non-blocking, same as SDKs)
  // Use Cloudflare Worker endpoint (port 8787 for local, or Worker URL for production)
  // Token is optional - anonymous sessions can send logs without authentication
  // HTTP POST works independently of WebSocket - don't wait for WebSocket connection
  const sendLogViaHTTP = async (logData) => {
    try {
      // Determine ingest URL
      let ingestUrl;
      if (webUrl.includes('localhost') || webUrl.includes('127.0.0.1')) {
        // Local development - use Workers dev server
        ingestUrl = 'http://localhost:8787/api/v1/ingest';
      } else if (process.env.VIBEX_WORKER_URL) {
        // Use explicit Worker URL if set
        ingestUrl = `${process.env.VIBEX_WORKER_URL}/api/v1/ingest`;
      } else {
        // Production default - use Worker URL (not web URL)
        const defaultWorkerUrl = 'https://ingest.vibex.sh';
        ingestUrl = `${defaultWorkerUrl}/api/v1/ingest`;
      }
            
      // Build headers - only include Authorization if token exists
      const headers = {
        'Content-Type': 'application/json',
      };
      if (token) {
        headers['Authorization'] = `Bearer ${token}`;
      }
      
      const response = await fetch(ingestUrl, {
        method: 'POST',
        headers,
        body: JSON.stringify({
          sessionId,
          logs: [logData],
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        const errorMessage = errorData.message || response.statusText || 'Unknown error';
        
        console.error(`\n  ✗ HTTP ${response.status}: ${errorMessage}`);
        
        // Handle specific error cases
        if (response.status === 401) {
          if (errorMessage.includes('expired')) {
            console.error('\n  🔑 Token Expired');
            console.error('  Your authentication token has expired.');
            console.error('  💡 Run: npx vibex-sh login');
            console.error('');
          } else if (errorMessage.includes('Invalid') || errorMessage.includes('invalid')) {
            console.error('\n  🔑 Invalid Token');
            console.error('  Your authentication token is invalid or missing.');
            console.error('  💡 Run: npx vibex-sh login');
            console.error('');
          } else {
            console.error('\n  🔑 Unauthorized');
            console.error(`  ${errorMessage}`);
            console.error('  💡 Run: npx vibex-sh login');
            console.error('');
          }
        } else if (response.status === 400) {
          console.error('\n  📝 Bad Request');
          console.error(`  ${errorMessage}`);
          if (errorMessage.includes('sessionId')) {
            console.error('  💡 Make sure you provided a valid session ID with -s or --session');
          } else if (errorMessage.includes('logs')) {
            console.error('  💡 Make sure you are sending valid log data');
          }
          console.error('');
        } else if (response.status === 403) {
          if (errorMessage.includes('History Limit')) {
            console.error('\n  🚫 History Limit Reached');
            console.error(`  ${errorMessage}`);
            if (errorData.upgradeRequired) {
              console.error('  💡 Upgrade to Pro to unlock 30 days retention');
              console.error('  🌐 Visit: https://vibex.sh/pricing');
            }
            console.error('');
          } else if (errorMessage.includes('access') || errorMessage.includes('belongs')) {
            console.error('\n  🚫 Access Denied');
            console.error(`  ${errorMessage}`);
            console.error('  💡 This session belongs to another user or is not accessible');
            console.error('  💡 Make sure you are using the correct token and session ID');
            console.error('');
          } else if (errorMessage.includes('archived')) {
            console.error('\n  🚫 Session Archived');
            console.error(`  ${errorMessage}`);
            console.error('  💡 This session is archived and cannot accept new logs');
            console.error('');
          } else {
            console.error('\n  🚫 Forbidden');
            console.error(`  ${errorMessage}`);
            console.error('');
          }
        } else if (response.status === 404) {
          console.error('\n  🔍 Session Not Found');
          console.error(`  ${errorMessage}`);
          console.error('  💡 Make sure the session ID is correct');
          console.error('  💡 Check if the session exists in your dashboard');
          console.error('');
        } else if (response.status === 429) {
          console.error('\n  ⚠️  Rate Limit Exceeded');
          console.error(`  ${errorMessage}`);
          if (errorData.retryAfter) {
            console.error(`  ⏱️  Retry after: ${errorData.retryAfter} seconds`);
          }
          console.error('');
        } else if (response.status >= 500) {
          console.error('\n  🔴 Server Error');
          console.error(`  ${errorMessage}`);
          console.error('  💡 This is a server-side issue. Please try again later.');
          console.error('  💡 If the problem persists, contact support');
          console.error('');
        } else {
          console.error(`  ${errorMessage}`);
          console.error('');
        }
      } else {
        const result = await response.json().catch(() => ({}));
        console.log(`  ✓ Log sent successfully (processed: ${result.processed || 1})`);
      }
    } catch (error) {
      console.error(`  ✗ Error sending log to ${ingestUrl}:`, error.message);
    }
  };

  // Start WebSocket connection
  connectWebSocket();

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false,
  });

  rl.on('line', (line) => {
    const trimmedLine = line.trim();
    if (!trimmedLine) {
      return;
    }

    let logData;
    try {
      const parsed = JSON.parse(trimmedLine);
      logData = {
        type: 'json',
        payload: parsed,
        timestamp: Date.now(),
      };
    } catch (e) {
      logData = {
        type: 'text',
        payload: trimmedLine,
        timestamp: Date.now(),
      };
    }

    // Send logs via HTTP POST immediately - don't wait for WebSocket
    // WebSocket is only for receiving logs and auth codes, not required for sending
    sendLogViaHTTP(logData);
  });

  rl.on('close', async () => {
    // Wait for queued logs to be sent
    const waitForQueue = () => {
      return new Promise((resolve) => {
        if (logQueue.length === 0) {
          resolve();
        } else {
          setTimeout(() => waitForQueue().then(resolve), 100);
        }
      });
    };
    
    await waitForQueue();
    
    console.log('\n  Stream ended. Closing connection...\n');
    
    // Cancel any pending reconnection attempts
    if (reconnectTimeout) {
      clearTimeout(reconnectTimeout);
      reconnectTimeout = null;
    }
    
    // Graceful shutdown - wait for close handshake
    await closeWebSocket();
    
    // Give a moment for any final cleanup
    setTimeout(() => process.exit(0), 100);
  });

  process.on('SIGINT', async () => {
    console.log('\n  Interrupted. Closing connection...\n');
    
    // Cancel any pending reconnection attempts
    if (reconnectTimeout) {
      clearTimeout(reconnectTimeout);
      reconnectTimeout = null;
    }
    
    // Graceful shutdown
    await closeWebSocket();
    
    process.exit(0);
  });
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});

